apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
  - resources:
      - credentials.boeing.boeing.ai
      - users.boeing.boeing.ai
      - identities.boeing.boeing.ai
      - mcpoauthtokens.boeing.boeing.ai
      - mcpoauthpendingstates.boeing.boeing.ai
      - mcpauditlogs.boeing.boeing.ai
      - policyviolations.boeing.boeing.ai
      - properties.boeing.boeing.ai
    providers:
      - kms:
          apiVersion: v2
          name: google-cloud-kms
          endpoint: unix:///tmp/gcp-cred-socket.sock
      - identity: {} # this fallback allows reading unencrypted secrets;
        # for example, during initial migration
